name: Validate Branch Name

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
    - 'main'

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          if [[ ! "$BRANCH_NAME" =~ ^feature\/[a-z0-9-]+$ ]]; then
            echo "Error: Wrong branch name"
            exit 1
          fi
        shell: bash
